name: Node CI+CD

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - run: npm install
    - run: npm run build

    - name: Copy to production server
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.privateKey }}
      with:
        source: "dist"
        target: "~/wordpress/wp-content/themes/nucssa-theme/"
        overwrite: true
