name: Node CI+CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Setup Node
      uses: actions/setup-node@v1
      with: 
        node-version: '12.x'
        
    - run: npm install
    - run: npm run build
      
    - name: Copy to production server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "dist"
        target: "~/wordpress/wp-content/themes/nucssa-theme/"
