name: PR - PHP Composer CI CD

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: composer install

    - name: Build
      run: composer dump-autoload -o

    - name: Deploy to Dev Server (https://dev.nucssa.org)
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.DEVHOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.privateKey }}
      with:
        source: "./*.php,./style.css,./screenshot.png,inc,vendor,views"
        target: "~/wordpress/wp-content/themes/nucssa-theme/"
        overwrite: true
